nar_common/static/nar_ui/nar.less
Changed the color of the toggle sites button triangle to match the ones on the map.
=> mrb triangle color change

nar_common/static/nar_ui/coastal/map.js, nar_common/static/nar_ui/map.js
controls in the sites page and in the coastal page. In the sites page,
since the filter can change, they need to be set in the
beforegetfeatureinfo event.
I also did some removing spaces and replacing with tabs.
=> Added cql_filter parameter to the vendorParams for the getFeatureInfo

nar_common/static/nar_ui/nar.less, nar_common/templates/nar_ui/download.html
Made the Triangle match the site color
=> Triangle Color change

nar_common/static/nar_ui/nar.less
Added the -ms-transform shiv so the triangles in the help prompts are oriented the correct way
=> ms-transform

nar_common/static/nar_ui/full_report/fullReportTree.js, nar_common/static/nar_ui/full_report/main.js, nar_common/static/nar_ui/plots/ConcentrationPlot.js, nar_common/templates/nar_ui/full_report.html
detailed graphs page. Also modified the Annual flow concentration plot
yaxis label.
=> Modified the labels and associated help on the selection tree on the

nar_common/templates/base.html
Added both our and USGS GA scripts to application. @isuftin mind verifying I didn't screw it up?
=> GA added to website

nar_common/templates/base.html
Removed the GA from the compressed JS files
=> new GA spot

nar_common/templates/nar_ui/slds/gulf_sites.sld
sites to be displayed. Adjusted the placement of labels accordingly.
=> Updated the gulf_sites.sld. This now uses qw_id to identify specific

nar_common/static/nar_ui/nar.less, nar_common/templates/nar_ui/mississippi.html
=> Added content to the map legend popover help. Made the map legend label

nar_common/static/nar_ui/plots/PlotUtils.js, nar_common/static/nar_ui/plots/sample_concentration_plot.js
Censored values are indicated on plot.
=> NAWQAAN-54

nar_common/example_local_settings.py, nar_common/settings_context_processor.py, nar_common/static/nar_ui/commons/SiteIdentificationControl.js, nar_common/static/nar_ui/map.js, nar_common/static/nar_ui/mississippi/ContributionDisplay.js, nar_common/static/nar_ui/mississippi/main.js, nar_common/static/nar_ui/siteFilter.js, nar_common/static/nar_ui/tests/siteFilterSpec.js, nar_common/templates/base.html, nar_common/templates/nar_ui/full_report.html, nar_common/templates/nar_ui/summary.html, nar_common/urls.py
this, eliminated the use of BASE_URL in the application. Instead use
Django's {% url %} and {% static %} template tags.
=> Changed the urls for the detailed and summary graph pages. As part of

nar_common/static/nar_ui/coastal_region/main.js, nar_common/static/nar_ui/plots/coastalBasinPlot.js
load and yield.
For load, the average and 2013 data is now displayed with 3 digits
precision. I have not changed the yield so it's still displayed to 2
digits after the decimal.
=> The Rio Grande values will now be shown with 3 digits precision for both

nar_common/urls.py, nar_common/views.py
Added three health service urls.
=> Nawqaan 359

nar_common/static/nar_ui/download.js
stations starting with "1" before the ones starting with "0". To work
around this in updateSelect2Options, create an array of keys and then
sort them if desired. Then iterate over the keys to create the options.
=> For stations, the automatic iteration over the object was returning the

nar_common/static/nar_ui/plots/PlotUtils.js, nar_common/static/nar_ui/tests/PlotUtilsSpec.js
make sure the split is across water year and not calendar year. Update
PlotUtils to use water year to split the data.
=> Updated the test for PlotUtils.getDataSplitIntoCurrentAndPreviousYear to

nar_common/templates/nar_ui/home.html
Removed the words "Over Time" from home page title
=> Home page title change

nar_common/static/nar_ui/commons/OpenLayersIE11Fix.js, nar_common/templates/nar_ui/site.html
http://osgeo-org.1560.x6.nabble.com/WFS-and-IE-11-td5090636.html .
I can't test this locally because another IE11 issue crops up dealing
with cross site origin issues.
If this doesn't work, I will revert the change.
=> Fix for OL and IE11, referenced here:

nar_common/templates/base.html, nar_common/templates/nar_ui/home.html, nar_common/templates/nar_ui/site.html
There are small changes for titles in the application. They should be as follows:
Home page title: 
Tracking Water Quality of the Nation's Rivers and Streams
Title of site report button on home page:
Rivers and Streams Across the States
Navigation menu - Data --> Rivers and Streams Across the United States - Water Quality Summaries
Main Sites Page Title: Rivers and Streams Across the United States - Water Quality Summaries
and
Place a beta tag next to application title in the navigation bar and change title.
New title:
Water Quality Tracking - Beta Version
=> text and title changes

nar_common/templates/base.html, nar_common/templates/nar_ui/home.html, nar_common/templates/nar_ui/mississippi.html
in to of
added united to home sites page
removed summary from mississippi river basin across entire app
=> small text changes

nar_common/templates/base.html
Updated the contact email, the URL, and last updated date on the footer.
=> Footer Changes

nar_common/settings.py, nar_common/static/nar_ui/mississippi/main.js, nar_common/static/nar_ui/tests/coastalBasinPlotSpec.js, nar_common/static/nar_ui/tests/downloadsSpec.js, nar_common/templates/nar_ui/home.html
Eliminated some duplicate declarations of the current water year, centralizing on CONFIG.currentWaterYear.
=> Nawqaan 528

nar_common/templates/nar_ui/home.html
=> Revert "Englishing"

nar_common/static/nar_ui/nar.less, nar_common/templates/nar_ui/home.html
=> Revert "Nawqaan 512"

nar_common/static/nar_ui/handlebars/pesticides.handlebars, nar_common/static/nar_ui/js_lib/handlebars.js, nar_common/static/nar_ui/summary.less, nar_common/static/nar_ui/summary_report/main.js, nar_common/templates/nar_ui/summary.html
Have the ability to hover over blue text to see the exceeding pesticides.
@jiwalker-usgs I know my code to make it work for both human exceedance and aquatic exceedance is copy and paste, but could use some tips on how to make it more efficient.
=> hover over for pesticides

nar_common/static/nar_ui/summary.less, nar_common/static/nar_ui/summary_report/main.js, nar_common/templates/nar_ui/summary.html
@jkreft-usgs @cschroed-usgs not finished, but heres the charts building with the web service call. 
Will finish after the weekend.
=> hh aq pesticide comparison charts so far

nar_common/static/nar_ui/plots/sample_concentration_comparison_plot.js
=> Revert "enable x-axis title"

nar_common/static/nar_ui/summary.less, nar_common/static/nar_ui/summary_report/main.js
@jiwalker-usgs I know you helped me write most of this code, but want to give it once last look and see if its okay to go?
=> finished summary comparisons bar chart

nar_common/static/nar_ui/handlebars/freqUse.handlebars, nar_common/static/nar_ui/summary.less, nar_common/static/nar_ui/summary_report/main.js, nar_common/templates/nar_ui/summary.html
@jiwalker-usgs @jkreft-usgs I still need to get that function that detects that samples where taken but not detected, but heres the charts building and all that
=> detection frequency and use graph

nar_common/static/nar_ui/summary_report/main.js
@jkreft-usgs This is the last part of the detection frequency charts. Everything should be functioning as it should be
=> no detection label

nar_common/static/nar_ui/handlebars/freqUse.handlebars, nar_common/static/nar_ui/summary_report/main.js
@cschroed-usgs This has the bar percentage function and the if no data return fix(if thats a good fix.) Bar chart stopped showing up when it was wrapped in an if statement, so thought this was easier?
=> bar percentage change

nar_common/static/nar_ui/nar.less, nar_common/static/nar_ui/pesticide_report/tree.js
Simple CSS display none until we want this attribute back in the pesticide tree
=> most frequently detected hidden

nar_common/static/nar_ui/nar.less, nar_common/static/nar_ui/pesticide_report/tree.js
Saw my mistake as the most frequently detected was the option that was supposed to stay and the other were to be removed.
=> pesticide tree correction

nar_common/static/nar_ui/nar.less
Centered the bar labels and touched up the text underneath the bars as well.
=> streamflow bar labels

nar_common/templates/base.html, nar_common/templates/nar_ui/coastal.html, nar_common/templates/nar_ui/full_report.html, nar_common/templates/nar_ui/pesticide_report.html, nar_common/templates/nar_ui/region_coastal.html, nar_common/templates/nar_ui/site.html, nar_common/templates/nar_ui/summary.html
Replaced the download links for links to science base with all our data, when it goes public.
=> science base link for download buttons

nar_common/static/nar_ui/commons/SiteIdentificationControl.js, nar_common/static/nar_ui/nar.less, nar_common/templates/nar_ui/summary.html
switches detailed graphs text for Nutrient and Sediment Graphs
=> nutrient and sediment graphs

nar_common/templates/base.html, nar_common/templates/nar_ui/2001_2007_station_list.html
I just changed one of the fact sheets.
=> change to https

nar_common/static/nar_ui/commons/SiteIdentificationControl.js, nar_common/static/nar_ui/mississippi/main.js, nar_common/templates/nar_ui/coastal.html, nar_common/templates/nar_ui/pesticide_report.html
made a mistake in the commit message- these are just wording changes
=> Wording changes

nar_common/static/nar_ui/commons/SiteIdentificationControl.js, nar_common/static/nar_ui/nar.less, nar_common/static/nar_ui/summary_report/main.js, nar_common/templates/base.html, nar_common/templates/nar_ui/coastal.html, nar_common/templates/nar_ui/download.html, nar_common/templates/nar_ui/full_report.html, nar_common/templates/nar_ui/pesticide_report.html, nar_common/templates/nar_ui/region_coastal.html, nar_common/templates/nar_ui/site.html, nar_common/templates/nar_ui/summary.html
Going through visual changes for NAR hopefully the commit names are descriptive enough for the current small changes I made.
=> NAR Changes

nar_common/static/nar_ui/commons/SiteIdentificationControl.js, nar_common/static/nar_ui/mississippi/main.js, nar_common/templates/nar_ui/full_report.html, nar_common/templates/nar_ui/pesticide_report.html, nar_common/templates/nar_ui/summary.html, nar_ui/models.py, nar_ui/views.py
=> science base site specific download links

nar_common/static/nar_ui/nar.less, nar_common/static/nar_ui/pesticide_report/main.js, nar_common/static/nar_ui/pesticide_report/tree.js
I undid the css to hide the unwanted tree DOM elements. The DOM elements were originally generated dynamically based on the results of a time series data web service call. I prevented the DOM elements from being created in the first place by filtering out irrelevant data availability entries.
=> Nawqaan 682

nar_common/static/nar_ui/mapCommons.js
Trying to eliminate problems by switching from complicated XML parsing to simpler JSON parsing.
=> Attempting to fix QA Empty List Bug

nar_common/settings.py
This reverts commit 0db11d4e820caf579fa2ddd9e8d44b63d169b494.
=> Revert "Bumped water year"

nar_common/static/nar_ui/plots/coastalBasinPlot.js
=> Fixed Gulf Of Mexico Coastal page.
